website/__init__.py
from flask import Flask
from .database import get_user
from flask_socketio import SocketIO
from flask_login import LoginManager

ROOMS = ['global', 'help']


def create_app():
    global socketio, app

    app = Flask(__name__)
    app.config["SECRET_KEY"] = "thisisademoversion"

    socketio = SocketIO(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(email):
        return get_user(email)

    return socketio, app

website/auth.py
from .database import get_user, save_user
from .checks import check_email, check_password_match
from flask_login import login_user, login_required, logout_user, current_user
from flask import Blueprint, render_template, redirect, request, flash, url_for


auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return render_template("home.html", user=current_user)
    
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        if not check_email(email):
            return render_template("login.html", user=current_user)

        user = get_user(email)
        if user and user.check_password(password):
            flash("Logged in successfully!", category="success")
            login_user(user, remember=True)

            return redirect(url_for("views.home"))
        else:
            flash("Incorrect email or password.", category="error")

    return render_template("login.html", user=current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth.route("/signup", methods=["GET", "POST"])
def signup():
    if current_user.is_authenticated:
        return render_template("home.html", user=current_user)
    
    if request.method == "POST":
        email = request.form.get("email")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        user = get_user(email)
        
        if user is not None:
            flash("Email already in use!", category="error")
            
            return render_template("signup.html", user=current_user)
        

        if check_email(email) and check_password_match(password1, password2):
            new_user = save_user(email, password1)  

            login_user(new_user, remember=True)
            flash("Account created!", category="success")

            return redirect(url_for("views.home"))

    return render_template("signup.html", user=current_user)

website/views.py
from . import socketio, app
from .checks import check_username
from flask_login import current_user
from flask_login.utils import login_required
from flask_socketio import join_room, leave_room
from flask import Blueprint, render_template, request, redirect, url_for

views = Blueprint("views", __name__)


@views.route('/')
@login_required
def home():
    return render_template("home.html", user=current_user)


@views.route('/chat')
def chat():
    username = request.args.get('username')
    roomname = request.args.get('roomname')

    if username and check_username(username):
        return render_template("chat.html", roomname=roomname, username=username, user=current_user)
    return redirect(url_for('views.home'))


@socketio.on('send_message')
def handle_send_message_event(data):
    app.logger.info(
        f"\n\n{data['username']} has sent '{data['message']}' to room {data['roomname']}\n"
    )
    
    socketio.emit('receive_message', data, room=data['roomname'])


@socketio.on('join_room')
def handle_join_room_event(data):
    app.logger.info(
        f"\n\n{data['username']} has joined the room {data['roomname']}\n"
    )

    join_room(data['roomname'])
    socketio.emit('join_room_announcement', data, room=data['roomname'])


@socketio.on('leave_room')
def handle_leave_room_event(data):
    app.logger.info(
        f"\n\n{data['username']} has left the room {data['roomname']}\n"
    )
    
    leave_room(data['roomname'])
    socketio.emit('leave_room_announcement', data, room=data['roomname'])

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS Stylesheets -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- JS Scripts -->
    <script src="{{ url_for('static', filename='socketio.js') }}"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
        integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
        crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
        </script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
        </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"></script>

    <!-- Title of Each Page -->
    {% block head %}
    {% endblock %}

</head>

<body>
    <!-- NavBar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Chat</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% else %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signUp" href="/signup">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <!-- Flash Messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    <!-- Content of Each Page -->
    <center>
        {% block body %}
        {% endblock %}
    </center>

</body>

</html>

website/templates/chat.html
{% extends "base.html" %}

{% block head %}
<title>Chat App</title>
{% endblock %}

{% block body %}
<h2>Welcome to {{ roomname }} Chat Room</h2>

<div id="show_messages"></div>

<form id="get_message">
    <input type="text" id="message" placeholder="Type Here...">
    <button type="submit">SEND</button>
</form>

<script>
    const socket = io()

    socket.on('connect', function () {
        socket.emit('join_room', {
            username: "{{ username }}",
            roomname: "{{ roomname }}"
        })

        let messages = document.getElementById('message');
        document.getElementById('get_message').onsubmit = function (e) {
            e.preventDefault();
            let message = messages.value.trim();
            if (message) {
                socket.emit('send_message', {
                    username: "{{ username }}",
                    roomname: "{{ roomname }}",
                    message: message
                })
            }
            messages.value = '';
            messages.focus();
        }
    });

    window.onbeforeunload = function () {
        socket.emit('leave_room', {
            username: "{{ username }}",
            roomname: "{{ roomname }}"
        })
    };

    socket.on('receive_message', function (data) {
        console.log(data);
        const newNode = document.createElement('div');
        newNode.innerHTML = "<b>" + data.username + ":&nbsp;</b>" + data.message;
        document.getElementById('show_messages').appendChild(newNode);
    });

    socket.on('join_room_announcement', function (data) {
        console.log(data);
        const newNode = document.createElement('div');
        newNode.innerHTML = "<b>" + data.username + "</b> has joined the room.";
        document.getElementById('show_messages').appendChild(newNode);
    });

    socket.on('leave_room_announcement', function (data) {
        console.log(data);
        const newNode = document.createElement('div');
        newNode.innerHTML = `<b>${data.username}</b> has left the room`;
        document.getElementById('show_messages').appendChild(newNode);
    });
</script>

{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block head %}
<title>Chat App</title>
{% endblock %}

{% block body %}
<h3>Lobby</h3><br><br>

<form action="{{ url_for('views.chat') }}">
    <div>
        <label for="">Enter Username:</label>
        <input type="text" name="username">
    </div>

    <div>
        <input type="radio" id="global" name="roomname" value="global">
        <label for="global">Global</label><br>
        <input type="radio" id="help" name="roomname" value="help">
        <label for="help">Help</label>
    </div>

    <button type="submit">SUBMIT</button>
</form>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<form method="POST">
    <h3>Login</h3>
    <p>(Do not enter any sensitive information)</p><br>

    <div class="form-group col-sm-4">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
    </div>

    <div class="form-group col-sm-4">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" />
    </div>

    <br><button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}

{% block head %}
<title>Sign Up</title>
{% endblock %}

{% block body %}
<form method="post">
    <h3>Sign Up</h3>
    <p>(Do not enter any sensitive information)</p><br>

    <div class="form-group col-sm-4">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
    </div>

    <div class="form-group col-sm-4">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password" />
    </div>

    <div class="form-group col-sm-4">
        <label for="password2">Confirm Password</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password" />
    </div>

    <br><button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}